KinMEBDT_WJets_electron->SetLineColor(kGreen)
KinMEBDT_WJets_electron->Draw()
KinMEBDT_WJets_electron->GetYaxis()->SetRangeUser(0,160000)
KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeUp->SetLineColor(kRed)
KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeUp->Draw("same")
KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeDown->SetLineColor(kRed-2)
KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeDown->Draw("same")
KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeUp->SetLineColor(kBlue)
KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeUp->Draw("same")
KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeDown->SetLineColor(kBlue-2)
KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeDown->Draw("same")
TLegend* leg = new TLegend(0.6,0.6,1.0,1.0)
leg->AddEntry(KinMEBDT_WJets_electron,KinMEBDT_WJets_electron->GetName(),"lep")
leg->AddEntry(KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeUp,KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeUp->GetName(),"lep")
leg->AddEntry(KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeDown,KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeDown->GetName(),"lep")
leg->AddEntry(KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeUp,KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeUp->GetName(),"lep")
leg->AddEntry(KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeDown,KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeDown->GetName(),"lep")
leg->Draw("same")
