data = KinMEBDT_SingleEl_Data_electron
WJets = KinMEBDT_WJets_electron
WJets_scaleUp = KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeUp
WJets_scaleDown = KinMEBDT_WJets_electron_CMS_hww_lnujj_scale_shapeDown
WJets_matchingUp = KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeUp
WJets_matchingDown = KinMEBDT_WJets_electron_CMS_hww_lnujj_matching_shapeDown
TTbar = KinMEBDT_TTbar_electron
TTbar_topWeightUp = KinMEBDT_TTbar_electron_CMS_hww_lnujj_topPtWeight_shapeUp
TTbar_topWeightDown = KinMEBDT_TTbar_electron_CMS_hww_lnujj_topPtWeight_shapeDown
QCD = KinMEBDT_QCD_ElFULL_electron
QCD_qcdWeightUp = KinMEBDT_QCD_ElFULL_electron_CMS_hww_lnujj_QCDEtaWeight_shapeUp
QCD_qcdWeightDown = KinMEBDT_QCD_ElFULL_electron_CMS_hww_lnujj_QCDEtaWeight_shapeDown
WJets->Scale(data->Integral()/WJets->Integral())
WJets_scaleUp->Scale(data->Integral()/WJets_scaleUp->Integral())
WJets_scaleDown->Scale(data->Integral()/WJets_scaleDown->Integral())
WJets_matchingUp->Scale(data->Integral()/WJets_matchingUp->Integral())
WJets_matchingDown->Scale(data->Integral()/WJets_matchingDown->Integral())
TTbar->Scale(data->Integral()/TTbar->Integral())
TTbar_topWeightUp->Scale(data->Integral()/TTbar_topWeightUp->Integral())
TTbar_topWeightDown->Scale(data->Integral()/TTbar_topWeightDown->Integral())
QCD->Scale(data->Integral()/QCD->Integral())
QCD_qcdWeightUp->Scale(data->Integral()/QCD_qcdWeightUp->Integral())
QCD_qcdWeightDown->Scale(data->Integral()/QCD_qcdWeightDown->Integral())
WJets->SetMarkerColor(2)
WJets_scaleUp->SetMarkerColor(3)
WJets_scaleDown->SetMarkerColor(4)
WJets_matchingUp->SetMarkerColor(5)
WJets_matchingDown->SetMarkerColor(6)
TTbar->SetMarkerColor(7)
TTbar_topWeightUp->SetMarkerColor(8)
TTbar_topWeightDown->SetMarkerColor(9)
QCD->SetMarkerColor(11)
QCD_qcdWeightUp->SetMarkerColor(12)
QCD_qcdWeightDown->SetMarkerColor(13)
WJets->SetLineColor(2)
WJets_scaleUp->SetLineColor(3)
WJets_scaleDown->SetLineColor(4)
WJets_matchingUp->SetLineColor(5)
WJets_matchingDown->SetLineColor(6)
TTbar->SetLineColor(7)
TTbar_topWeightUp->SetLineColor(8)
TTbar_topWeightDown->SetLineColor(9)
QCD->SetLineColor(11)
QCD_qcdWeightUp->SetLineColor(12)
QCD_qcdWeightDown->SetLineColor(13)
data->Draw()
WJets->Draw("same")
WJets_scaleUp->Draw("same")
WJets_scaleDown->Draw("same")
WJets_matchingUp->Draw("same")
WJets_matchingDown->Draw("same")
TTbar->Draw("same")
TTbar_topWeightUp->Draw("same")
TTbar_topWeightDown->Draw("same")
QCD->Draw("same")
QCD_qcdWeightUp->Draw("same")
QCD_qcdWeightDown->Draw("same")
TLegend* leg = new TLegend(0.6,0.3,0.9,0.9)
leg->AddEntry(data,"data","lep")
leg->AddEntry(WJets,"WJets","lep")
leg->AddEntry(WJets_scaleUp,"WJets ScaleUp","lep")
leg->AddEntry(WJets_scaleDown,"WJets ScaleDown","lep")
leg->AddEntry(WJets_matchingUp,"WJets MatchingUp","lep")
leg->AddEntry(WJets_matchingDown,"WJets MatchingDown","lep")
leg->AddEntry(TTbar,"TTbar","lep")
leg->AddEntry(TTbar_topWeightUp,"TTbar topWeightUp","lep")
leg->AddEntry(TTbar_topWeightDown,"TTbar topWeightDown","lep")
leg->AddEntry(QCD,"QCD","lep")
leg->AddEntry(QCD_qcdWeightUp,"QCD qcdWeightUp","lep")
leg->AddEntry(QCD_qcdWeightDown,"QCD qcdWeightDown","lep")
leg->Draw("same")
